"""initial schema

Revision ID: 1bdf339d7c34
Revises:
Create Date: 2026-09-12 17:31:06.535308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.database import SCHEMA


revision: str = '1bdf339d7c34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(f'CREATE SCHEMA IF NOT EXISTS "{SCHEMA}"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA,
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA,
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True, schema=SCHEMA)
    op.create_table('expense_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('pre_retirement_annual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('post_retirement_annual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], [f'{SCHEMA}.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA,
    )
    op.create_table('household_assumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('inflation_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('expected_return', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('safe_withdrawal_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('lifestyle_preset', sa.Enum('MODEST', 'COMFORTABLE', 'LUXURIOUS', 'CUSTOM', name='lifestylepreset', schema=SCHEMA), nullable=False),
    sa.Column('filing_status', sa.Enum('SINGLE', 'MARRIED_FILING_JOINTLY', name='filingstatus', schema=SCHEMA), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], [f'{SCHEMA}.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id'),
    schema=SCHEMA,
    )
    op.create_table('household_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', name='householdrole', schema=SCHEMA), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], [f'{SCHEMA}.households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [f'{SCHEMA}.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA,
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.Enum('SELF', 'PARTNER', name='relationship', schema=SCHEMA), nullable=False),
    sa.Column('current_age', sa.Integer(), nullable=False),
    sa.Column('retirement_age', sa.Integer(), nullable=False),
    sa.Column('life_expectancy', sa.Integer(), nullable=False),
    sa.Column('social_security_monthly_estimate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('social_security_claim_age', sa.Integer(), nullable=False),
    sa.Column('pension_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], [f'{SCHEMA}.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA,
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], [f'{SCHEMA}.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA,
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('TRADITIONAL_401K', 'ROTH_401K', 'TRADITIONAL_IRA', 'ROTH_IRA', 'HSA', 'BROKERAGE', 'CASH', name='accounttype', schema=SCHEMA), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('annual_contribution', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('annual_employer_match', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_return_override', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], [f'{SCHEMA}.households.id'], ),
    sa.ForeignKeyConstraint(['person_id'], [f'{SCHEMA}.people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts', schema=SCHEMA)
    op.drop_table('scenarios', schema=SCHEMA)
    op.drop_table('people', schema=SCHEMA)
    op.drop_table('household_members', schema=SCHEMA)
    op.drop_table('household_assumptions', schema=SCHEMA)
    op.drop_table('expense_categories', schema=SCHEMA)
    op.drop_index(op.f('ix_users_email'), table_name='users', schema=SCHEMA)
    op.drop_table('users', schema=SCHEMA)
    op.drop_table('households', schema=SCHEMA)
    # ### end Alembic commands ###
